<?php
/**
 * WPLostPasswordAddAction
 *
 * @package Offsetwp\Hook\WordPress\Action
 */

declare( strict_types=1 );

namespace Offsetwp\Hook\WordPress\Action;

/**
 * Fires before the lost password form.
 *
 * @since 1.5.1
 * @since 5.1.0 Added the `$errors` parameter.
 */
abstract class WPLostPasswordAddAction extends \Offsetwp\Hook\Support\AddAction {
	/**
	 * The name of the action to add the callback to.
	 *
	 * @var string
	 */
	public string $hook_name = 'lost_password';

	/**
	 * The callback to be run when the action is called.
	 *
	 * @var string
	 */
	public int $hook_priority = 10;

	/**
	 * Optional. Used to specify the order in which the functions associated with a particular action are executed. Lower numbers correspond with earlier execution, and functions with the same priority are executed in the order in which they were added to the action. Default 10.
	 *
	 * @var string
	 */
	public int $hook_accepted_args = 1;


	/**
	 * The hook execution method
	 *
	 * @param \WP_Error $errors A <code>WP_Error</code> object containing any errors generated by using invalid credentials. Note that the error object may not contain any errors.
	 */
	abstract public function execute( $errors );
}
